title: "Piotr Kołaczkowski"
author: "Piotr Kołaczkowski"
description: "My blog about computer programming"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

sidebar: true                # show a sidebar instead of the usual header
show_excerpts: true          # show article excerpts on the home page
show_related: true           # show the previous and next links after every post
show_description: false      # show the site description in the sidebar
show_title: true             # always keep the site title visible

# Styling

dark_header: true            # always keep the header dark
minimal: false               # use simpler style

# Menu
navigation:
  - {file: "index.html", icon: home}
  - {file: "about.md", icon: address-card}

external:                    # see http://fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:pkolaczk@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/pkolaczk"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/pkolaczk"}
  - {title: RSS, icon: rss, url: "/feed.xml"}

comments:
  disqus: true
  disqus_shortname: piotr_kolaczkowski       # see https://disqus.com/
#  isso_domain: ""                           # see https://posativ.org/isso/

plugins: 
  - jekyll-feed
  

